"""add branch and department ownership to investigations

Revision ID: 03af6fc47af5
Revises: d1f781c212f0
Create Date: 2026-08-15 12:46:51.871647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03af6fc47af5'
down_revision: Union[str, Sequence[str], None] = 'd1f781c212f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.add_column('investigations', sa.Column('department_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_investigations_branch_id'), 'investigations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_investigations_department_id'), 'investigations', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_index(op.f('ix_investigations_department_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_branch_id'), table_name='investigations')
    op.drop_column('investigations', 'department_id')
    op.drop_column('investigations', 'branch_id')
    # ### end Alembic commands ###
