"""add investigation history table

Revision ID: 9ecc0c4c40be
Revises: d7cb71df869c
Create Date: 2026-07-17 12:02:21.350041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ecc0c4c40be"
down_revision: Union[str, Sequence[str], None] = "d7cb71df869c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigation_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("next_action", sa.String(length=500), nullable=False),
        sa.Column("changed_by", sa.String(length=36), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["investigations.case_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigation_history_case_id"),
        "investigation_history",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_history_changed_at"),
        "investigation_history",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_history_changed_by"),
        "investigation_history",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_history_status"),
        "investigation_history",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_investigation_history_status"), table_name="investigation_history"
    )
    op.drop_index(
        op.f("ix_investigation_history_changed_by"), table_name="investigation_history"
    )
    op.drop_index(
        op.f("ix_investigation_history_changed_at"), table_name="investigation_history"
    )
    op.drop_index(
        op.f("ix_investigation_history_case_id"), table_name="investigation_history"
    )
    op.drop_table("investigation_history")
    # ### end Alembic commands ###
