"""add investigation ownership

Revision ID: d7cb71df869c
Revises: 3765eb6de05d
Create Date: 2026-07-13 19:41:41.856515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d7cb71df869c"
down_revision: Union[str, Sequence[str], None] = "3765eb6de05d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigations", sa.Column("created_by", sa.String(length=36), nullable=False)
    )
    op.create_index(
        op.f("ix_investigations_created_by"),
        "investigations",
        ["created_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_investigations_created_by"), table_name="investigations")
    op.drop_column("investigations", "created_by")
    # ### end Alembic commands ###
